# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lession_editor_GUI_tab.ui'
#
# Created: Mon Jan 12 23:13:14 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1133, 808)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.frame_10 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.load_data_BTN = QtGui.QPushButton(self.frame_10)
        self.load_data_BTN.setObjectName(_fromUtf8("load_data_BTN"))
        self.horizontalLayout_14.addWidget(self.load_data_BTN)
        self.label_12 = QtGui.QLabel(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.file_path_L = QtGui.QLabel(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_path_L.sizePolicy().hasHeightForWidth())
        self.file_path_L.setSizePolicy(sizePolicy)
        self.file_path_L.setObjectName(_fromUtf8("file_path_L"))
        self.horizontalLayout_14.addWidget(self.file_path_L)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_18 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_26 = QtGui.QLabel(self.frame_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_14.addWidget(self.label_26)
        self.line_7 = QtGui.QFrame(self.frame_18)
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_14.addWidget(self.line_7)
        self.frame_22 = QtGui.QFrame(self.frame_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName(_fromUtf8("frame_22"))
        self.gridLayout = QtGui.QGridLayout(self.frame_22)
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_29 = QtGui.QLabel(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 2, 0, 1, 1)
        self.win_width_LE = QtGui.QLineEdit(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.win_width_LE.sizePolicy().hasHeightForWidth())
        self.win_width_LE.setSizePolicy(sizePolicy)
        self.win_width_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.win_width_LE.setObjectName(_fromUtf8("win_width_LE"))
        self.gridLayout.addWidget(self.win_width_LE, 0, 1, 1, 1)
        self.voxel_size_LE = QtGui.QLineEdit(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voxel_size_LE.sizePolicy().hasHeightForWidth())
        self.voxel_size_LE.setSizePolicy(sizePolicy)
        self.voxel_size_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.voxel_size_LE.setObjectName(_fromUtf8("voxel_size_LE"))
        self.gridLayout.addWidget(self.voxel_size_LE, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 0, 0, 1, 1)
        self.win_level_LE = QtGui.QLineEdit(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.win_level_LE.sizePolicy().hasHeightForWidth())
        self.win_level_LE.setSizePolicy(sizePolicy)
        self.win_level_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.win_level_LE.setObjectName(_fromUtf8("win_level_LE"))
        self.gridLayout.addWidget(self.win_level_LE, 1, 1, 1, 1)
        self.win_wdth_SL = QtGui.QSlider(self.frame_22)
        self.win_wdth_SL.setMaximum(1000)
        self.win_wdth_SL.setProperty("value", 350)
        self.win_wdth_SL.setOrientation(QtCore.Qt.Horizontal)
        self.win_wdth_SL.setObjectName(_fromUtf8("win_wdth_SL"))
        self.gridLayout.addWidget(self.win_wdth_SL, 0, 2, 1, 1)
        self.win_lvl_SL = QtGui.QSlider(self.frame_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.win_lvl_SL.sizePolicy().hasHeightForWidth())
        self.win_lvl_SL.setSizePolicy(sizePolicy)
        self.win_lvl_SL.setMinimum(-1000)
        self.win_lvl_SL.setMaximum(1000)
        self.win_lvl_SL.setProperty("value", 50)
        self.win_lvl_SL.setOrientation(QtCore.Qt.Horizontal)
        self.win_lvl_SL.setObjectName(_fromUtf8("win_lvl_SL"))
        self.gridLayout.addWidget(self.win_lvl_SL, 1, 2, 1, 1)
        self.voxel_size_SB = QtGui.QScrollBar(self.frame_22)
        self.voxel_size_SB.setMaximum(10)
        self.voxel_size_SB.setProperty("value", 2)
        self.voxel_size_SB.setOrientation(QtCore.Qt.Horizontal)
        self.voxel_size_SB.setObjectName(_fromUtf8("voxel_size_SB"))
        self.gridLayout.addWidget(self.voxel_size_SB, 2, 2, 1, 1)
        self.verticalLayout_14.addWidget(self.frame_22)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.frame_19 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_15.addWidget(self.checkBox_2)
        self.line_8 = QtGui.QFrame(self.frame_19)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_15.addWidget(self.line_8)
        self.frame_20 = QtGui.QFrame(self.frame_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_25 = QtGui.QLabel(self.frame_20)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 2, 1, 1, 1)
        self.bilateral_spatial_LE = QtGui.QLineEdit(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bilateral_spatial_LE.sizePolicy().hasHeightForWidth())
        self.bilateral_spatial_LE.setSizePolicy(sizePolicy)
        self.bilateral_spatial_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bilateral_spatial_LE.setObjectName(_fromUtf8("bilateral_spatial_LE"))
        self.gridLayout_2.addWidget(self.bilateral_spatial_LE, 2, 2, 1, 1)
        self.sigma_SL = QtGui.QSlider(self.frame_20)
        self.sigma_SL.setMaximum(10)
        self.sigma_SL.setProperty("value", 1)
        self.sigma_SL.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_SL.setObjectName(_fromUtf8("sigma_SL"))
        self.gridLayout_2.addWidget(self.sigma_SL, 0, 3, 1, 1)
        self.bilateral_range_LE = QtGui.QLineEdit(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bilateral_range_LE.sizePolicy().hasHeightForWidth())
        self.bilateral_range_LE.setSizePolicy(sizePolicy)
        self.bilateral_range_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bilateral_range_LE.setObjectName(_fromUtf8("bilateral_range_LE"))
        self.gridLayout_2.addWidget(self.bilateral_range_LE, 1, 2, 1, 1)
        self.gaussian_sigma_LE = QtGui.QLineEdit(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaussian_sigma_LE.sizePolicy().hasHeightForWidth())
        self.gaussian_sigma_LE.setSizePolicy(sizePolicy)
        self.gaussian_sigma_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gaussian_sigma_LE.setObjectName(_fromUtf8("gaussian_sigma_LE"))
        self.gridLayout_2.addWidget(self.gaussian_sigma_LE, 0, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.frame_20)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 1, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.frame_20)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 0, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.frame_20)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_2.addWidget(self.radioButton_3, 3, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.frame_20)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 3, 1, 1, 1)
        self.tv_weight_LE = QtGui.QLineEdit(self.frame_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tv_weight_LE.sizePolicy().hasHeightForWidth())
        self.tv_weight_LE.setSizePolicy(sizePolicy)
        self.tv_weight_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tv_weight_LE.setObjectName(_fromUtf8("tv_weight_LE"))
        self.gridLayout_2.addWidget(self.tv_weight_LE, 3, 2, 1, 1)
        self.sigma_range_SL = QtGui.QSlider(self.frame_20)
        self.sigma_range_SL.setMaximum(100)
        self.sigma_range_SL.setProperty("value", 100)
        self.sigma_range_SL.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_range_SL.setObjectName(_fromUtf8("sigma_range_SL"))
        self.gridLayout_2.addWidget(self.sigma_range_SL, 1, 3, 1, 1)
        self.sigma_spatial_SL = QtGui.QSlider(self.frame_20)
        self.sigma_spatial_SL.setMaximum(50)
        self.sigma_spatial_SL.setProperty("value", 15)
        self.sigma_spatial_SL.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_spatial_SL.setObjectName(_fromUtf8("sigma_spatial_SL"))
        self.gridLayout_2.addWidget(self.sigma_spatial_SL, 2, 3, 1, 1)
        self.tv_weight_SL = QtGui.QSlider(self.frame_20)
        self.tv_weight_SL.setMaximum(1000)
        self.tv_weight_SL.setProperty("value", 100)
        self.tv_weight_SL.setOrientation(QtCore.Qt.Horizontal)
        self.tv_weight_SL.setObjectName(_fromUtf8("tv_weight_SL"))
        self.gridLayout_2.addWidget(self.tv_weight_SL, 3, 3, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_20)
        self.verticalLayout_11.addWidget(self.frame_19)
        self.frame_15 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_15)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_20 = QtGui.QLabel(self.frame_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_13.addWidget(self.label_20)
        self.line_5 = QtGui.QFrame(self.frame_15)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_13.addWidget(self.line_5)
        self.frame_11 = QtGui.QFrame(self.frame_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.alpha_LE = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha_LE.sizePolicy().hasHeightForWidth())
        self.alpha_LE.setSizePolicy(sizePolicy)
        self.alpha_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.alpha_LE.setObjectName(_fromUtf8("alpha_LE"))
        self.gridLayout_3.addWidget(self.alpha_LE, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.beta_LE = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beta_LE.sizePolicy().hasHeightForWidth())
        self.beta_LE.setSizePolicy(sizePolicy)
        self.beta_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.beta_LE.setObjectName(_fromUtf8("beta_LE"))
        self.gridLayout_3.addWidget(self.beta_LE, 1, 1, 1, 1)
        self.alpha_SL = QtGui.QSlider(self.frame_11)
        self.alpha_SL.setMaximum(20)
        self.alpha_SL.setProperty("value", 3)
        self.alpha_SL.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_SL.setObjectName(_fromUtf8("alpha_SL"))
        self.gridLayout_3.addWidget(self.alpha_SL, 0, 2, 1, 1)
        self.beta_SL = QtGui.QSlider(self.frame_11)
        self.beta_SL.setMaximum(20)
        self.beta_SL.setProperty("value", 1)
        self.beta_SL.setOrientation(QtCore.Qt.Horizontal)
        self.beta_SL.setObjectName(_fromUtf8("beta_SL"))
        self.gridLayout_3.addWidget(self.beta_SL, 1, 2, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_11)
        self.run_BTN = QtGui.QPushButton(self.frame_15)
        self.run_BTN.setMaximumSize(QtCore.QSize(150, 16777215))
        self.run_BTN.setObjectName(_fromUtf8("run_BTN"))
        self.verticalLayout_13.addWidget(self.run_BTN)
        self.verticalLayout_11.addWidget(self.frame_15)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.color_model_T = QtGui.QWidget()
        self.color_model_T.setObjectName(_fromUtf8("color_model_T"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.color_model_T)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frame_6 = QtGui.QFrame(self.color_model_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame_9 = QtGui.QFrame(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.perc_LE = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perc_LE.sizePolicy().hasHeightForWidth())
        self.perc_LE.setSizePolicy(sizePolicy)
        self.perc_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.perc_LE.setObjectName(_fromUtf8("perc_LE"))
        self.gridLayout_4.addWidget(self.perc_LE, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_9)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.k_std_h_LE = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k_std_h_LE.sizePolicy().hasHeightForWidth())
        self.k_std_h_LE.setSizePolicy(sizePolicy)
        self.k_std_h_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.k_std_h_LE.setObjectName(_fromUtf8("k_std_h_LE"))
        self.gridLayout_4.addWidget(self.k_std_h_LE, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_9)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.k_std_t_LE = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k_std_t_LE.sizePolicy().hasHeightForWidth())
        self.k_std_t_LE.setSizePolicy(sizePolicy)
        self.k_std_t_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.k_std_t_LE.setObjectName(_fromUtf8("k_std_t_LE"))
        self.gridLayout_4.addWidget(self.k_std_t_LE, 2, 1, 1, 1)
        self.frac_SL = QtGui.QSlider(self.frame_9)
        self.frac_SL.setMaximum(100)
        self.frac_SL.setProperty("value", 30)
        self.frac_SL.setOrientation(QtCore.Qt.Horizontal)
        self.frac_SL.setObjectName(_fromUtf8("frac_SL"))
        self.gridLayout_4.addWidget(self.frac_SL, 0, 2, 1, 1)
        self.heal_std_k_SL = QtGui.QSlider(self.frame_9)
        self.heal_std_k_SL.setMaximum(10)
        self.heal_std_k_SL.setProperty("value", 3)
        self.heal_std_k_SL.setOrientation(QtCore.Qt.Horizontal)
        self.heal_std_k_SL.setObjectName(_fromUtf8("heal_std_k_SL"))
        self.gridLayout_4.addWidget(self.heal_std_k_SL, 1, 2, 1, 1)
        self.tum_std_k_SL = QtGui.QSlider(self.frame_9)
        self.tum_std_k_SL.setMaximum(10)
        self.tum_std_k_SL.setProperty("value", 3)
        self.tum_std_k_SL.setOrientation(QtCore.Qt.Horizontal)
        self.tum_std_k_SL.setObjectName(_fromUtf8("tum_std_k_SL"))
        self.gridLayout_4.addWidget(self.tum_std_k_SL, 2, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.calculate_models_BTN = QtGui.QPushButton(self.frame_6)
        self.calculate_models_BTN.setMaximumSize(QtCore.QSize(150, 16777215))
        self.calculate_models_BTN.setObjectName(_fromUtf8("calculate_models_BTN"))
        self.verticalLayout_9.addWidget(self.calculate_models_BTN)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.histogram_F = QtGui.QFrame(self.color_model_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_F.sizePolicy().hasHeightForWidth())
        self.histogram_F.setSizePolicy(sizePolicy)
        self.histogram_F.setMinimumSize(QtCore.QSize(0, 100))
        self.histogram_F.setFrameShape(QtGui.QFrame.Box)
        self.histogram_F.setObjectName(_fromUtf8("histogram_F"))
        self.verticalLayout_10.addWidget(self.histogram_F)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.color_model_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.frame_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.hypo_mean_SB = QtGui.QSpinBox(self.frame_3)
        self.hypo_mean_SB.setMaximum(256)
        self.hypo_mean_SB.setObjectName(_fromUtf8("hypo_mean_SB"))
        self.horizontalLayout_2.addWidget(self.hypo_mean_SB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.hypo_std_SB = QtGui.QSpinBox(self.frame_3)
        self.hypo_std_SB.setObjectName(_fromUtf8("hypo_std_SB"))
        self.horizontalLayout_5.addWidget(self.hypo_std_SB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.color_model_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.line_2 = QtGui.QFrame(self.frame_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.heal_mean_SB = QtGui.QSpinBox(self.frame_4)
        self.heal_mean_SB.setMaximum(256)
        self.heal_mean_SB.setSingleStep(1)
        self.heal_mean_SB.setObjectName(_fromUtf8("heal_mean_SB"))
        self.horizontalLayout_6.addWidget(self.heal_mean_SB)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.heal_std_SB = QtGui.QSpinBox(self.frame_4)
        self.heal_std_SB.setObjectName(_fromUtf8("heal_std_SB"))
        self.horizontalLayout_7.addWidget(self.heal_std_SB)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.color_model_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.line_3 = QtGui.QFrame(self.frame_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.hyper_mean_SB = QtGui.QSpinBox(self.frame_5)
        self.hyper_mean_SB.setMaximum(256)
        self.hyper_mean_SB.setObjectName(_fromUtf8("hyper_mean_SB"))
        self.horizontalLayout_8.addWidget(self.hyper_mean_SB)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_11 = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.hyper_std_SB = QtGui.QSpinBox(self.frame_5)
        self.hyper_std_SB.setObjectName(_fromUtf8("hyper_std_SB"))
        self.horizontalLayout_9.addWidget(self.hyper_std_SB)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.color_model_T, _fromUtf8(""))
        self.objects_T = QtGui.QWidget()
        self.objects_T.setObjectName(_fromUtf8("objects_T"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.objects_T)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_12 = QtGui.QFrame(self.objects_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_17 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.max_area_LE = QtGui.QLineEdit(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_area_LE.sizePolicy().hasHeightForWidth())
        self.max_area_LE.setSizePolicy(sizePolicy)
        self.max_area_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.max_area_LE.setObjectName(_fromUtf8("max_area_LE"))
        self.gridLayout_5.addWidget(self.max_area_LE, 1, 1, 1, 1)
        self.min_area_LE = QtGui.QLineEdit(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_area_LE.sizePolicy().hasHeightForWidth())
        self.min_area_LE.setSizePolicy(sizePolicy)
        self.min_area_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.min_area_LE.setObjectName(_fromUtf8("min_area_LE"))
        self.gridLayout_5.addWidget(self.min_area_LE, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.min_area_SL = QtGui.QSlider(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_area_SL.sizePolicy().hasHeightForWidth())
        self.min_area_SL.setSizePolicy(sizePolicy)
        self.min_area_SL.setMaximum(50)
        self.min_area_SL.setProperty("value", 2)
        self.min_area_SL.setOrientation(QtCore.Qt.Horizontal)
        self.min_area_SL.setObjectName(_fromUtf8("min_area_SL"))
        self.gridLayout_5.addWidget(self.min_area_SL, 0, 2, 1, 1)
        self.max_area_SL = QtGui.QSlider(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_area_SL.sizePolicy().hasHeightForWidth())
        self.max_area_SL.setSizePolicy(sizePolicy)
        self.max_area_SL.setMaximum(50)
        self.max_area_SL.setProperty("value", 30)
        self.max_area_SL.setOrientation(QtCore.Qt.Horizontal)
        self.max_area_SL.setObjectName(_fromUtf8("max_area_SL"))
        self.gridLayout_5.addWidget(self.max_area_SL, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.min_comp_LE = QtGui.QLineEdit(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_comp_LE.sizePolicy().hasHeightForWidth())
        self.min_comp_LE.setSizePolicy(sizePolicy)
        self.min_comp_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.min_comp_LE.setObjectName(_fromUtf8("min_comp_LE"))
        self.gridLayout_5.addWidget(self.min_comp_LE, 2, 1, 1, 1)
        self.min_comp_SL = QtGui.QSlider(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_comp_SL.sizePolicy().hasHeightForWidth())
        self.min_comp_SL.setSizePolicy(sizePolicy)
        self.min_comp_SL.setMaximum(100)
        self.min_comp_SL.setSingleStep(1)
        self.min_comp_SL.setProperty("value", 50)
        self.min_comp_SL.setOrientation(QtCore.Qt.Horizontal)
        self.min_comp_SL.setObjectName(_fromUtf8("min_comp_SL"))
        self.gridLayout_5.addWidget(self.min_comp_SL, 2, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 3, 0, 1, 1)
        self.comp_fact_SB = QtGui.QScrollBar(self.frame_12)
        self.comp_fact_SB.setMaximum(10)
        self.comp_fact_SB.setProperty("value", 3)
        self.comp_fact_SB.setOrientation(QtCore.Qt.Horizontal)
        self.comp_fact_SB.setObjectName(_fromUtf8("comp_fact_SB"))
        self.gridLayout_5.addWidget(self.comp_fact_SB, 3, 2, 1, 1)
        self.comp_fact_LE = QtGui.QLineEdit(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comp_fact_LE.sizePolicy().hasHeightForWidth())
        self.comp_fact_LE.setSizePolicy(sizePolicy)
        self.comp_fact_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comp_fact_LE.setObjectName(_fromUtf8("comp_fact_LE"))
        self.gridLayout_5.addWidget(self.comp_fact_LE, 3, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.scrollArea = QtGui.QScrollArea(self.objects_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 512))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.objects_T, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_2 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.left_view_btns_F = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_view_btns_F.sizePolicy().hasHeightForWidth())
        self.left_view_btns_F.setSizePolicy(sizePolicy)
        self.left_view_btns_F.setMinimumSize(QtCore.QSize(0, 20))
        self.left_view_btns_F.setFrameShape(QtGui.QFrame.StyledPanel)
        self.left_view_btns_F.setFrameShadow(QtGui.QFrame.Raised)
        self.left_view_btns_F.setObjectName(_fromUtf8("left_view_btns_F"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.left_view_btns_F)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.view_1_BTN = QtGui.QPushButton(self.left_view_btns_F)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_1_BTN.sizePolicy().hasHeightForWidth())
        self.view_1_BTN.setSizePolicy(sizePolicy)
        self.view_1_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.view_1_BTN.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Eye.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_1_BTN.setIcon(icon)
        self.view_1_BTN.setIconSize(QtCore.QSize(24, 24))
        self.view_1_BTN.setObjectName(_fromUtf8("view_1_BTN"))
        self.horizontalLayout_12.addWidget(self.view_1_BTN)
        self.show_im_1_BTN = QtGui.QPushButton(self.left_view_btns_F)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_im_1_BTN.sizePolicy().hasHeightForWidth())
        self.show_im_1_BTN.setSizePolicy(sizePolicy)
        self.show_im_1_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_im_1_BTN.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Stock graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_im_1_BTN.setIcon(icon1)
        self.show_im_1_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_im_1_BTN.setObjectName(_fromUtf8("show_im_1_BTN"))
        self.horizontalLayout_12.addWidget(self.show_im_1_BTN)
        self.show_labels_1_BTN = QtGui.QPushButton(self.left_view_btns_F)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_labels_1_BTN.sizePolicy().hasHeightForWidth())
        self.show_labels_1_BTN.setSizePolicy(sizePolicy)
        self.show_labels_1_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_labels_1_BTN.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Blue tag.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_labels_1_BTN.setIcon(icon2)
        self.show_labels_1_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_labels_1_BTN.setObjectName(_fromUtf8("show_labels_1_BTN"))
        self.horizontalLayout_12.addWidget(self.show_labels_1_BTN)
        self.show_contours_1_BTN = QtGui.QPushButton(self.left_view_btns_F)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_contours_1_BTN.sizePolicy().hasHeightForWidth())
        self.show_contours_1_BTN.setSizePolicy(sizePolicy)
        self.show_contours_1_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_contours_1_BTN.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Brush.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_contours_1_BTN.setIcon(icon3)
        self.show_contours_1_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_contours_1_BTN.setObjectName(_fromUtf8("show_contours_1_BTN"))
        self.horizontalLayout_12.addWidget(self.show_contours_1_BTN)
        self.verticalLayout_7.addWidget(self.left_view_btns_F)
        self.frame_7 = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prob_heal_1_CB = QtGui.QCheckBox(self.frame_7)
        self.prob_heal_1_CB.setObjectName(_fromUtf8("prob_heal_1_CB"))
        self.horizontalLayout_3.addWidget(self.prob_heal_1_CB)
        self.prob_hypo_1_CB = QtGui.QCheckBox(self.frame_7)
        self.prob_hypo_1_CB.setObjectName(_fromUtf8("prob_hypo_1_CB"))
        self.horizontalLayout_3.addWidget(self.prob_hypo_1_CB)
        self.prob_hyper_1_CB = QtGui.QCheckBox(self.frame_7)
        self.prob_hyper_1_CB.setObjectName(_fromUtf8("prob_hyper_1_CB"))
        self.horizontalLayout_3.addWidget(self.prob_hyper_1_CB)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.frame_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.right_view_btns_F = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_view_btns_F.sizePolicy().hasHeightForWidth())
        self.right_view_btns_F.setSizePolicy(sizePolicy)
        self.right_view_btns_F.setMinimumSize(QtCore.QSize(0, 20))
        self.right_view_btns_F.setFrameShape(QtGui.QFrame.StyledPanel)
        self.right_view_btns_F.setFrameShadow(QtGui.QFrame.Raised)
        self.right_view_btns_F.setObjectName(_fromUtf8("right_view_btns_F"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.right_view_btns_F)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.view_2_BTN = QtGui.QPushButton(self.right_view_btns_F)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_2_BTN.sizePolicy().hasHeightForWidth())
        self.view_2_BTN.setSizePolicy(sizePolicy)
        self.view_2_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.view_2_BTN.setText(_fromUtf8(""))
        self.view_2_BTN.setIcon(icon)
        self.view_2_BTN.setIconSize(QtCore.QSize(24, 24))
        self.view_2_BTN.setObjectName(_fromUtf8("view_2_BTN"))
        self.horizontalLayout_13.addWidget(self.view_2_BTN)
        self.show_im_2_BTN = QtGui.QPushButton(self.right_view_btns_F)
        self.show_im_2_BTN.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_im_2_BTN.sizePolicy().hasHeightForWidth())
        self.show_im_2_BTN.setSizePolicy(sizePolicy)
        self.show_im_2_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_im_2_BTN.setText(_fromUtf8(""))
        self.show_im_2_BTN.setIcon(icon1)
        self.show_im_2_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_im_2_BTN.setObjectName(_fromUtf8("show_im_2_BTN"))
        self.horizontalLayout_13.addWidget(self.show_im_2_BTN)
        self.show_labels_2_BTN = QtGui.QPushButton(self.right_view_btns_F)
        self.show_labels_2_BTN.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_labels_2_BTN.sizePolicy().hasHeightForWidth())
        self.show_labels_2_BTN.setSizePolicy(sizePolicy)
        self.show_labels_2_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_labels_2_BTN.setText(_fromUtf8(""))
        self.show_labels_2_BTN.setIcon(icon2)
        self.show_labels_2_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_labels_2_BTN.setObjectName(_fromUtf8("show_labels_2_BTN"))
        self.horizontalLayout_13.addWidget(self.show_labels_2_BTN)
        self.show_contours_2_BTN = QtGui.QPushButton(self.right_view_btns_F)
        self.show_contours_2_BTN.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_contours_2_BTN.sizePolicy().hasHeightForWidth())
        self.show_contours_2_BTN.setSizePolicy(sizePolicy)
        self.show_contours_2_BTN.setMinimumSize(QtCore.QSize(40, 0))
        self.show_contours_2_BTN.setText(_fromUtf8(""))
        self.show_contours_2_BTN.setIcon(icon3)
        self.show_contours_2_BTN.setIconSize(QtCore.QSize(24, 24))
        self.show_contours_2_BTN.setObjectName(_fromUtf8("show_contours_2_BTN"))
        self.horizontalLayout_13.addWidget(self.show_contours_2_BTN)
        self.verticalLayout_8.addWidget(self.right_view_btns_F)
        self.frame_8 = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.prob_heal_2_CB = QtGui.QCheckBox(self.frame_8)
        self.prob_heal_2_CB.setObjectName(_fromUtf8("prob_heal_2_CB"))
        self.horizontalLayout_10.addWidget(self.prob_heal_2_CB)
        self.prob_hypo_2_CB = QtGui.QCheckBox(self.frame_8)
        self.prob_hypo_2_CB.setObjectName(_fromUtf8("prob_hypo_2_CB"))
        self.horizontalLayout_10.addWidget(self.prob_hypo_2_CB)
        self.prob_hyper_2_CB = QtGui.QCheckBox(self.frame_8)
        self.prob_hyper_2_CB.setObjectName(_fromUtf8("prob_hyper_2_CB"))
        self.horizontalLayout_10.addWidget(self.prob_hyper_2_CB)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.viewer_F = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_F.sizePolicy().hasHeightForWidth())
        self.viewer_F.setSizePolicy(sizePolicy)
        self.viewer_F.setMinimumSize(QtCore.QSize(0, 0))
        self.viewer_F.setFrameShape(QtGui.QFrame.Box)
        self.viewer_F.setObjectName(_fromUtf8("viewer_F"))
        self.verticalLayout_2.addWidget(self.viewer_F)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.slice_number_LBL = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_number_LBL.sizePolicy().hasHeightForWidth())
        self.slice_number_LBL.setSizePolicy(sizePolicy)
        self.slice_number_LBL.setMinimumSize(QtCore.QSize(100, 0))
        self.slice_number_LBL.setObjectName(_fromUtf8("slice_number_LBL"))
        self.horizontalLayout_11.addWidget(self.slice_number_LBL)
        self.slice_scrollB = QtGui.QScrollBar(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_scrollB.sizePolicy().hasHeightForWidth())
        self.slice_scrollB.setSizePolicy(sizePolicy)
        self.slice_scrollB.setOrientation(QtCore.Qt.Horizontal)
        self.slice_scrollB.setObjectName(_fromUtf8("slice_scrollB"))
        self.horizontalLayout_11.addWidget(self.slice_scrollB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.load_data_BTN.setText(_translate("MainWindow", "Load data", None))
        self.label_12.setText(_translate("MainWindow", "Serie:", None))
        self.file_path_L.setText(_translate("MainWindow", "not loaded", None))
        self.label_26.setText(_translate("MainWindow", "GENERAL PARAMETERS", None))
        self.label_29.setText(_translate("MainWindow", "voxel size [mm] =", None))
        self.win_width_LE.setText(_translate("MainWindow", "350", None))
        self.voxel_size_LE.setText(_translate("MainWindow", "2", None))
        self.label_28.setText(_translate("MainWindow", "window level =", None))
        self.label_27.setText(_translate("MainWindow", "window width =", None))
        self.win_level_LE.setText(_translate("MainWindow", "50", None))
        self.checkBox_2.setText(_translate("MainWindow", "SMOOTHING", None))
        self.label_25.setText(_translate("MainWindow", "spatial =", None))
        self.bilateral_spatial_LE.setText(_translate("MainWindow", "15", None))
        self.bilateral_range_LE.setText(_translate("MainWindow", "0.05", None))
        self.gaussian_sigma_LE.setText(_translate("MainWindow", "1", None))
        self.label_24.setText(_translate("MainWindow", "range =", None))
        self.radioButton.setText(_translate("MainWindow", "Gaussian blurr: ", None))
        self.radioButton_2.setText(_translate("MainWindow", "Bilateral: ", None))
        self.label_23.setText(_translate("MainWindow", "sigma =", None))
        self.radioButton_3.setText(_translate("MainWindow", "TV: ", None))
        self.label_30.setText(_translate("MainWindow", "weight =", None))
        self.tv_weight_LE.setText(_translate("MainWindow", "0.05", None))
        self.label_20.setText(_translate("MainWindow", "LOCALIZATION", None))
        self.alpha_LE.setText(_translate("MainWindow", "3", None))
        self.label_21.setText(_translate("MainWindow", "alpha =", None))
        self.label_22.setText(_translate("MainWindow", "beta =", None))
        self.beta_LE.setText(_translate("MainWindow", "1", None))
        self.run_BTN.setText(_translate("MainWindow", "Run localization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "MAIN", None))
        self.perc_LE.setText(_translate("MainWindow", "30", None))
        self.label_13.setText(_translate("MainWindow", "heal. std k =", None))
        self.k_std_h_LE.setText(_translate("MainWindow", "3", None))
        self.label.setText(_translate("MainWindow", "fraction [%]=", None))
        self.label_14.setText(_translate("MainWindow", "lession std k =", None))
        self.k_std_t_LE.setText(_translate("MainWindow", "3", None))
        self.calculate_models_BTN.setText(_translate("MainWindow", "Calculate models", None))
        self.label_3.setText(_translate("MainWindow", "hypodense", None))
        self.label_6.setText(_translate("MainWindow", "mean =", None))
        self.label_7.setText(_translate("MainWindow", "std =", None))
        self.label_4.setText(_translate("MainWindow", "healthy", None))
        self.label_8.setText(_translate("MainWindow", "mean =", None))
        self.label_9.setText(_translate("MainWindow", "std =", None))
        self.label_5.setText(_translate("MainWindow", "hyperdense", None))
        self.label_10.setText(_translate("MainWindow", "mean =", None))
        self.label_11.setText(_translate("MainWindow", "std =", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.color_model_T), _translate("MainWindow", "Color Model", None))
        self.label_17.setText(_translate("MainWindow", "min. compactness [%] =", None))
        self.max_area_LE.setText(_translate("MainWindow", "30", None))
        self.min_area_LE.setText(_translate("MainWindow", "2", None))
        self.label_15.setText(_translate("MainWindow", "min. area [cm^2] =", None))
        self.label_16.setText(_translate("MainWindow", "max. area [cm^2] =", None))
        self.min_comp_LE.setText(_translate("MainWindow", "50", None))
        self.label_18.setText(_translate("MainWindow", "Compact factor =", None))
        self.comp_fact_LE.setText(_translate("MainWindow", "3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.objects_T), _translate("MainWindow", "Objects", None))
        self.label_2.setText(_translate("MainWindow", "VIEWER", None))
        self.prob_heal_1_CB.setText(_translate("MainWindow", "P(heal)", None))
        self.prob_hypo_1_CB.setText(_translate("MainWindow", "P(hypo)", None))
        self.prob_hyper_1_CB.setText(_translate("MainWindow", "P(hyper)", None))
        self.prob_heal_2_CB.setText(_translate("MainWindow", "P(heal)", None))
        self.prob_hypo_2_CB.setText(_translate("MainWindow", "P(hypo)", None))
        self.prob_hyper_2_CB.setText(_translate("MainWindow", "P(hyper)", None))
        self.slice_number_LBL.setText(_translate("MainWindow", "slice # =", None))

